#!/bin/bash

########
##Built to quickly get my fresh Fedora install up to speed
########

##Update the base system before adding rpmfusion repo
sudo dnf -y update
sudo dnf install -y https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

##Get the desired system hostname
read -p "Enter Computer Name: " computername
sudo hostnamectl hostname "$computername"

##Install a few packages.
sudo dnf install -y gnome-tweaks gnome-extensions-app papirus-icon-theme google-roboto-* fira-code* gnome-shell-extension-user-theme gnome-shell-extension-dash-to-dock gnome-shell-extension-blur-my-shell vim-enhanced awscli2

##Install Visual Studio Code
sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
sudo dnf install -y code

## Install Docker Engine
sudo dnf config-manager addrepo --from-repofile=https://download.docker.com/linux/fedora/docker-ce.repo
sudo dnf -y install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
sudo systemctl start docker
sudo systemctl enable docker
sudo usermod -aG docker $USER #Add current user to docker group
newgrp docker #Apply the new group to the current session

## Install Terraform CLI
sudo dnf config-manager addrepo --from-repofile=https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
sudo dnf -y install terraform

##Set a few desktop options
gsettings set org.gnome.desktop.interface icon-theme 'Papirus'
gsettings set org.gnome.desktop.wm.preferences button-layout 'appmenu:minimize,close'
gsettings set org.gnome.shell.extensions.dash-to-dock dock-position 'LEFT'

##Set termincal opacity to 85%
gsettings set org.gnome.Terminal.Legacy.Settings headerbar '@mb false'
profile_id=$(gsettings get org.gnome.Terminal.ProfilesList default | tr -d \')
gsettings set "org.gnome.Terminal.Legacy.Profile:/org/gnome/Terminal/Profiles:/:$profile_id/" use-transparent-background true
gsettings set "org.gnome.Terminal.Legacy.Profile:/org/gnome/Terminal/Profiles:/:$profile_id/" background-transparency-percent 15